spring:
  application:
    name: forage-midas
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    com.jpmc.midascore: DEBUG

server:
  port: 8080

# Additional configurations can be added here as needed.